global:
  scrape_interval: 10s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus:9090
- job_name: node
  static_configs:
  - targets:
    - node-exporter:9100
- job_name: 'go-backend'
  static_configs:
  - targets: ['go-backend:3000']
- job_name: 'pulsar-broker'
  static_configs:
  - targets: ['pulsar:8080']
