apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: pulsar
  name: pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pulsar
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.network/backend-network: "true"
        io.kompose.service: pulsar
    spec:
      containers:
        - args:
            - bin/pulsar
            - standalone
          image: apachepulsar/pulsar:latest
          name: pulsar
          ports:
            - containerPort: 6650
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
